### ISSUE TITLE
New local range for transports_or_maintains_localization_of

### ISSUE THREAD

**Issue by rachhuntley** [geneontology/annotation_extensions#60]
Hi,

Could you please make the necessary changes that would allow use of RNAcentral idenfiers with this relation? 

Thanks,
Rachael.

**Comment by dosumis** [comment]
Added SO:0000673 transcript to local range.  @tonysawfordebi - is this sufficient?

**Comment by rachhuntley** [comment]
Could you also make necessary changes to allow IntAct complex IDs with this relation - I've just realised I need this as well.

Thanks!

**Comment by dosumis** [comment]
Might work already:

[This relation](https://github.com/geneontology/annotation_extensions/blob/master/doc/transports_or_maintains_localization_of.md) already has 'GO:0005575 : cellular_component' in the local range, which covers 'protein complex'. 
The [mapping file entry for InTact](https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml#L1075) includes type: 'protein complex'.

Give it a try and let me know if it fails.

**Comment by rachhuntley** [comment]
OK thanks. I'm wating for a new term before I can try it.

**Comment by tonysawfordebi** [comment]
To allow the used of RNAcentral IDs, I think that you need to use CHEBI:33697 (ribonucleic acid) in the local_range, rather than SO:0000673, because that's what's specified in https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml as the entity type for RNAcentral.

Or, possibly, you could modify http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/experimental/upper/go-upper.obo to make CHEBI:33697 a subclass of SO:0000673, but a) I don't know whether that's actually correct, and b) I don't know what knock-on effects that might have.

**Comment by rachhuntley** [comment]
Hi, Could I please get an update on the status of this? I still can add RNAcentral IDs or IntAct complex IDs to this relation.
Thanks!

**Comment by dosumis** [comment]
- I have added the CHEBI ID.  Should be visible tomorrow. (We will add the bridging to SO as part of work to bring in more upper ontology - but didn't want you to have to wait for this).
- Not clear to me why InTact IDs are not allowed.  All CC's should be allowed and InTact IDs are typed as a GO:'protein complex' in the YAML file.  Perhaps also an issue that there is a type link to - 'molecular interaction' -  BET:0000013  ???

Tony - do you have any way to debug this?  I could try adding 'protein complex' to the local range, but seems like this shouldn't be necessary.

**Comment by tonysawfordebi** [comment]
I believe that I've fixed the problem with IntAct IDs, but can't test at the moment because most of the interesting bits of the EBI are off-line for hardware maintenance/upgrade (which, incidentally, means that today's QuickGO update has just been terminated, so any changes made yesterday won't be appearing today). If everything comes back to life at the promised time this afternoon, I'll get the fix in place ready for tonight's update.

**Comment by rachhuntley** [comment]
I'm now able to add IntAct and RNAcentral IDs for this relation.

Thanks!
